name: build-bazel

on: [push, workflow_dispatch]

jobs:
  bazel:
    runs-on: [self-hosted, macos]

    steps:
      - uses: actions/checkout@v3

      - uses: bazelbuild/setup-bazelisk@v2

      - name: Mount bazel cache # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: bazel clean
        run: bazel clean
      
      - name: build bazel
        run: |
          bazel build //...
      
      - name: test
        run: ./bazel-bin/call-highs-example