name: test-clang-format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: 'app/ highs/Highs.h ./highs/lp_data ./highs/mip ./highs/model ./highs/simplex ./highs/presolve  ./highs/simplex ./highs/util'
        #./highs/test ./interfaces'
        extensions: 'h,cpp,c'
        clangFormatVersion: 14
